const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./MasterDB.db');

db.serialize(() => {
  db.run(`CREATE TABLE IF NOT EXISTS MEMBERS (
    Member_id TEXT PRIMARY KEY,
    Branch_code VARCHAR(10),
    Joining_date DATE,
    Prefix TEXT,
    First_name TEXT,
    Middle_name TEXT,
    Last_name TEXT,
    Gender TEXT,
    Date_of_birth DATE,
    Education TEXT,
    Occupation TEXT,
    Marital_status TEXT,
    Religion TEXT,
    Category TEXT,
    If_other TEXT,
    Aadhar_no TEXT,
    Pan_no TEXT,
    Voter_no TEXT,
    Ration_no TEXT,
    Electricity_bill_no TEXT,
    Driving_license_no TEXT,
    Passport_no TEXT,
    Other_kyc TEXT,
    Father_name TEXT,
    Father_occupation TEXT,
    Father_age INTEGER,
    Mother_name TEXT,
    Mother_occupation TEXT,
    Mother_age INTEGER,
    Spouse_name TEXT,
    Spouse_occupation TEXT,
    Spouse_age INTEGER,
    Member_name_list TEXT,
    Emplyee_agent_no TEXT,
    Emplyee_agent_name TEXT,
    House_no TEXT,
    Galli TEXT,
    Street TEXT,
    Landmark TEXT,
    District TEXT,
    Taluka TEXT,
    State TEXT,
    Country TEXT,
    City TEXT,
    Pincode TEXT,
    Full_address TEXT,
    Phone_no TEXT,
    Telephone_no TEXT,
    Email_id TEXT,
    Nominee_full_name TEXT,
    Nominee_relation TEXT,
    Nominee_phone_no TEXT,
    Nominee_aadhar_no TEXT,
    Nominee_pan_no TEXT,
    Nominee_voter_no TEXT,
    Nominee_ration_no TEXT,
    Nominee_driving_license_no TEXT,
    Nominee_other_kyc TEXT,
    Nominee_full_address TEXT,
    Photo_image TEXT,
    Signature_image TEXT,
    Aadhar_image TEXT,
    Pan_image TEXT,
    Other_kyc_image TEXT,
    FOREIGN KEY (Branch_code) REFERENCES BRANCH(Branch_code)
  )`);
});

db.close();
